
name: CI/CD Pipeline


# on:
#   pull_request:
#     branches: [ main ]

jobs:
	build-test-deploy:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout code
				uses: actions/checkout@v4

			- name: Set up Python
				uses: actions/setup-python@v5
				with:
					python-version: '3.13'

			- name: Install dependencies
				run: |
					python -m pip install --upgrade pip
					pip install -r requirements.txt

			- name: Run pre-commit checks
				run: pre-commit run --all-files

			- name: Run tests
				run: pytest tests/

			- name: Build Docker image
				run: docker build -t demand-forecast-dashboard .

			# Optional: Push Docker image to registry
			# - name: Login to DockerHub
			#   uses: docker/login-action@v3
			#   with:
			#     username: ${{ secrets.DOCKER_USERNAME }}
			#     password: ${{ secrets.DOCKER_PASSWORD }}
			# - name: Push image
			#   run: docker push demand-forecast-dashboard

			# Optional: Deploy step (add your cloud provider's action here)
			# - name: Deploy to cloud
			#   run: echo "Deploy step here"
